### ISSUE TITLE
Update mtslack notification

### ISSUE THREAD

**Issue by thadjbullet** [mallowigi/mtslack#49]
Update `mtslack` notification appears even after update.
Reload slack doesn't help.
macOs 10.15.7

**Comment by mallowigi** [comment]
What version of mtslack do you have ?

**Comment by thadjbullet** [comment]
13.8.0

**Comment by mallowigi** [comment]
This might be a cache problem. You might need to wait a few days to get the new uncached version, as of now it might be running the old version with the notification.

At the very most you could still reinstall Slack...

**Comment by mallowigi** [comment]
Ok I managed to reproduce and there were two reasons for this issue:
- Because it compares strings and not numbers, for some reason a double quote got in the way, making the comparison always false
- I need to work a bit on the versioning process, as currently I need to update the version in the code BEFORE I publish a new version, so that the npm package contains the most updated version. However after publishing the package, the version will go up, meaning that by the time I'm pushing another client update the version will be behind again...

For now I'm not planning on adding new stuff so that should be ok, but that definitely needs an improvement 😅
